---
# nextcloud-secrets is pre-created by bootstrap-cluster.sh before Flux reconciles.
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 10m
  dependsOn:
    - name: ingress-nginx
      namespace: ingress-nginx
    - name: keycloak
      namespace: keycloak
  chart:
    spec:
      chart: ./charts/nextcloud
      sourceRef:
        kind: GitRepository
        name: freeit
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    companyId: "${company_id}"
    domain: "${company_domain}"
