companyId: ""
domain: ""

keycloak:
  image: quay.io/keycloak/keycloak:26.1.0
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 1Gi

postgresql:
  image: postgres:16-alpine
  storage: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
