"""
Seeders — one per app. Each seeder injects artefacts idempotently.

Files (Nextcloud WebDAV): fully implemented.
Mail (IMAP):              stub — wired in E3.2.
Calendar (CalDAV):        stub — wired in E3.2.
"""

from __future__ import annotations

import imaplib
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import TYPE_CHECKING

import requests

if TYPE_CHECKING:
    from provisioner.seed.spec import CalendarArtefact, FileArtefact, MailArtefact


# ── Files seeder (Nextcloud WebDAV) ──────────────────────────────────────────

class FilesSeeder:
    """
    Uploads Markdown files to Nextcloud via WebDAV.
    Idempotent: checks if the file already exists (HEAD) before uploading.
    Uses per-user app passwords generated by bootstrap-realm.sh (E1.3).
    """

    def __init__(self, base_url: str, app_password_fn: "AppPasswordFn") -> None:
        """
        base_url:        e.g. https://files.acme-demo.yourdemo.com
        app_password_fn: callable(email) → Nextcloud app password for that user
        """
        self._base = base_url.rstrip("/")
        self._app_password = app_password_fn

    def seed(self, artefacts: list[FileArtefact]) -> dict[str, str]:
        results: dict[str, str] = {}
        for art in artefacts:
            outcome = self._upload(art)
            results[art.webdav_path] = outcome
        return results

    def _upload(self, art: FileArtefact) -> str:
        password = self._app_password(art.owner_email)
        webdav_url = f"{self._base}/remote.php/dav/files/{art.owner_email}{art.webdav_path}"
        auth = (art.owner_email, password)

        # Idempotency: skip if file already exists.
        head = requests.head(webdav_url, auth=auth, timeout=15)
        if head.status_code == 200:
            return "skipped"

        # Ensure parent directory exists.
        parent = art.webdav_path.rsplit("/", 1)[0]
        if parent:
            self._mkdirs(art.owner_email, password, parent)

        resp = requests.put(
            webdav_url,
            data=art.content.encode("utf-8"),
            auth=auth,
            headers={"Content-Type": "text/markdown; charset=utf-8"},
            timeout=30,
        )
        resp.raise_for_status()
        return "created"

    def _mkdirs(self, username: str, password: str, path: str) -> None:
        """MKCOL all path segments that don't yet exist."""
        auth = (username, password)
        parts = path.strip("/").split("/")
        for i in range(1, len(parts) + 1):
            segment = "/".join(parts[:i])
            url = f"{self._base}/remote.php/dav/files/{username}/{segment}"
            head = requests.head(url, auth=auth, timeout=10)
            if head.status_code == 404:
                requests.request("MKCOL", url, auth=auth, timeout=10)


# ── Mail seeder (IMAP inject) ─────────────────────────────────────────────────

class MailSeeder:
    """
    Injects pre-composed emails directly into each employee's INBOX via IMAP.
    Requires IMAP access to the mail server — wired in E3.2.

    STUB: raises NotImplementedError until E3.2 provides IMAP credentials/config.
    """

    def __init__(self, imap_host: str, imap_port: int = 993) -> None:
        self._host = imap_host
        self._port = imap_port

    def seed(self, artefacts: list[MailArtefact]) -> dict[str, str]:
        # TODO (E3.2): replace stub with real IMAP inject.
        # Pattern:
        #   conn = imaplib.IMAP4_SSL(self._host, self._port)
        #   conn.login(art.to_email, app_password)
        #   msg = _build_mime(art)
        #   conn.append("INBOX", None, None, msg.as_bytes())
        results = {}
        for art in artefacts:
            print(f"    [stub/mail] would inject welcome email to {art.to_email}")
            results[art.to_email] = "stub"
        return results


# ── Calendar seeder (CalDAV) ──────────────────────────────────────────────────

class CalendarSeeder:
    """
    Creates calendar events via CalDAV.
    Idempotent: uses the event UID as the resource name — PUT is a no-op if identical.
    Requires CalDAV access — wired in E3.2.

    STUB: raises NotImplementedError until E3.2 provides CalDAV endpoint/config.
    """

    def __init__(self, caldav_base_url: str) -> None:
        self._base = caldav_base_url

    def seed(self, artefacts: list[CalendarArtefact]) -> dict[str, str]:
        # TODO (E3.2): replace stub with real CalDAV PUT.
        # Pattern:
        #   url = f"{self._base}/{art.owner_email}/calendar/{art.uid}.ics"
        #   ics = _build_ics(art)
        #   requests.put(url, data=ics, auth=..., headers={"Content-Type": "text/calendar"})
        results = {}
        for art in artefacts:
            print(f"    [stub/cal]  would create '{art.summary}' for {art.owner_email}")
            results[art.uid] = "stub"
        return results


# ── Type alias ────────────────────────────────────────────────────────────────

from typing import Callable
AppPasswordFn = Callable[[str], str]


# ── MIME helpers (used when mail seeder is fully wired) ───────────────────────

def _build_mime(art: MailArtefact) -> MIMEMultipart:
    msg = MIMEMultipart("alternative")
    msg["Subject"] = art.subject
    msg["From"] = f"noreply@{art.to_email.split('@')[1]}"
    msg["To"] = art.to_email
    msg.attach(MIMEText(art.body_text, "plain"))
    msg.attach(MIMEText(art.body_html, "html"))
    return msg
