"""
Seed data specification.

Defines exactly what artefacts are created in each app for a freshly
provisioned company. Everything is derived from the CompanySpec — no
hardcoded content.

Artefact inventory per company:
  Files (Nextcloud WebDAV):
    - /onboarding/<first_name>_<last_name>/Welcome.md          — per onboarding target
    - /onboarding/<first_name>_<last_name>/Team_Directory.md   — per onboarding target
    - /shared/Company_Handbook.md                              — one per company

  Mail (IMAP inject — E3.2 fills this in):
    - Welcome email in each employee's INBOX

  Calendar (CalDAV — E3.2 fills this in):
    - "Company All-Hands" recurring event (weekly, next 4 occurrences)
    - "1:1 with Manager" for each employee who has a manager in the CSV
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date, timedelta

from provisioner.schema import CompanySpec, EmployeeRow, Role


@dataclass
class FileArtefact:
    """A file to upload to Nextcloud via WebDAV."""
    webdav_path: str   # relative to the user's root, e.g. /onboarding/Bob_Smith/Welcome.md
    content: str       # rendered Markdown
    owner_email: str   # Nextcloud username = employee email


@dataclass
class MailArtefact:
    """An email to inject into an employee's INBOX."""
    to_email: str
    subject: str
    body_text: str
    body_html: str


@dataclass
class CalendarArtefact:
    """A calendar event to create via CalDAV."""
    owner_email: str
    uid: str           # stable UID for idempotency
    summary: str
    description: str
    start: date
    end: date
    rrule: str | None = None   # e.g. "FREQ=WEEKLY;COUNT=4"


@dataclass
class SeedBundle:
    """All artefacts for one company. Generated by build_seed_bundle()."""
    files: list[FileArtefact]
    mails: list[MailArtefact]
    calendars: list[CalendarArtefact]


def build_seed_bundle(spec: CompanySpec, today: date | None = None) -> SeedBundle:
    """Derive all seed artefacts from a CompanySpec."""
    from provisioner.seed.renderer import render

    today = today or date.today()
    company = spec.company
    employees = spec.employees
    onboarding_targets = [e for e in employees if e.is_onboarding_target]

    # Build a lookup: email → manager (first manager in same department)
    managers = {e.email: e for e in employees if e.role == Role.manager}

    def find_manager(emp: EmployeeRow) -> EmployeeRow | None:
        for m in managers.values():
            if m.department == emp.department and m.email != emp.email:
                return m
        return None

    files: list[FileArtefact] = []
    mails: list[MailArtefact] = []
    calendars: list[CalendarArtefact] = []

    # ── Shared company handbook ───────────────────────────────────────────────
    files.append(FileArtefact(
        webdav_path="/shared/Company_Handbook.md",
        content=render("company_handbook.md.j2", company=company, employees=employees),
        owner_email=_admin_email(employees),
    ))

    # ── Per onboarding-target artefacts ───────────────────────────────────────
    for emp in onboarding_targets:
        slug = f"{emp.first_name}_{emp.last_name}"
        manager = find_manager(emp)

        ctx = dict(company=company, employee=emp, manager=manager, employees=employees, today=today)

        files.append(FileArtefact(
            webdav_path=f"/onboarding/{slug}/Welcome.md",
            content=render("welcome.md.j2", **ctx),
            owner_email=emp.email,
        ))
        files.append(FileArtefact(
            webdav_path=f"/onboarding/{slug}/Team_Directory.md",
            content=render("team_directory.md.j2", **ctx),
            owner_email=emp.email,
        ))

        mails.append(MailArtefact(
            to_email=emp.email,
            subject=f"Welcome to {company.company_name}!",
            body_text=render("welcome_email.txt.j2", **ctx),
            body_html=render("welcome_email.html.j2", **ctx),
        ))

        # All-hands weekly event
        calendars.append(CalendarArtefact(
            owner_email=emp.email,
            uid=f"all-hands-{company.company_id}",
            summary=f"{company.company_name} All-Hands",
            description="Weekly all-hands meeting for the whole company.",
            start=_next_monday(today),
            end=_next_monday(today) + timedelta(hours=1),
            rrule="FREQ=WEEKLY;COUNT=4",
        ))

        # 1:1 with manager if one exists
        if manager:
            calendars.append(CalendarArtefact(
                owner_email=emp.email,
                uid=f"one-on-one-{emp.email}-{manager.email}",
                summary=f"1:1 with {manager.first_name} {manager.last_name}",
                description=f"Regular 1:1 with your manager.",
                start=_next_tuesday(today),
                end=_next_tuesday(today) + timedelta(minutes=30),
                rrule="FREQ=WEEKLY;COUNT=4",
            ))

    return SeedBundle(files=files, mails=mails, calendars=calendars)


def _admin_email(employees: list[EmployeeRow]) -> str:
    for e in employees:
        if e.role == Role.admin:
            return e.email
    return employees[0].email


def _next_weekday(today: date, weekday: int) -> date:
    """Return the next occurrence of weekday (0=Mon, 1=Tue, …) after today."""
    days_ahead = weekday - today.weekday()
    if days_ahead <= 0:
        days_ahead += 7
    return today + timedelta(days=days_ahead)


def _next_monday(today: date) -> date:
    return _next_weekday(today, 0)


def _next_tuesday(today: date) -> date:
    return _next_weekday(today, 1)
